DOCKER_REGISTRY ?= quay.io
DOCKER_TAG ?= latest
DOCKER_ORG ?= strimzi

docker_build:
    docker build docker-image/ --build-arg version=${VERSION} -t ${DOCKER_REGISTRY}/strimzi/${PROJECT_NAME}:latest

docker_tag:
    docker tag ${DOCKER_REGISTRY}/strimzi/${PROJECT_NAME}:latest ${DOCKER_REGISTRY}/${DOCKER_ORG}/${PROJECT_NAME}:${DOCKER_TAG}

docker_push:
    docker push ${DOCKER_REGISTRY}/${DOCKER_ORG}/${PROJECT_NAME}:${DOCKER_TAG}
